# Generated by Django 5.2.12 on 2026-05-02 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0002_seed_demo_head'),
    ]

    operations = [
        migrations.AlterField(
            model_name='head',
            name='subscription_type',
            field=models.CharField(choices=[('demo', 'Demo'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='demo', help_text='Optional label for reporting. Access is not blocked by dates.', max_length=20),
        ),
    ]
