# Generated by Django 5.2.12 on 2026-05-02 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0003_head_subscription_help_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='head',
            name='expiry_notification_sent',
        ),
        migrations.RemoveField(
            model_name='head',
            name='subscription_type',
        ),
    ]
