# Generated by Django 5.2.12 on 2026-05-02 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0007_client_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=200)),
                ('owner_name', models.CharField(blank=True, default='', max_length=200)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('address', models.TextField(blank=True, default='')),
                ('salespoints_slug', models.SlugField(help_text='URL path fragment, typically "{hotel}-salespoints".', max_length=96, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='orgs.head')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branch_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
