# Generated by Django 5.2.12 on 2026-05-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0008_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='paused_by_head',
            field=models.BooleanField(default=False, help_text='When True, do not auto-activate outlet login after subscription renews.'),
        ),
    ]
