# Generated by Django 5.2.12 on 2026-05-02 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0009_branch_paused_by_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='subscription_period_start',
            field=models.DateField(blank=True, help_text='Start of current billed window; set when Head changes plan so end = this + plan days. If null, signup date (created_at) is used.', null=True),
        ),
    ]
